### ISSUE TITLE
Allow batch prediction

### ISSUE THREAD

**Issue by frascuchon** [recognai/biome-text#110]
The default batch prediction method defined in `allennlp.Predictor`  will not handle errors in text-to-instance transformation, failing into a global batch error if one single input cannot be predicted.

We need tackle those cases for properly apply batch prediction. We have 2 alternatives:

1. Implements a custom `predict_batch_json` handling empty instances
2. Make model pipeline (reader + architecture) robust to void  instances (We need to check if it's possible in terms of `allennlp` api  creating void `instances`

**Comment by dvsrepo** [comment]
Is this still relevant or can we close it?

**Comment by frascuchon** [comment]
New pipeline definition doesn't allow batch prediction. But we could define a new issue as feat proposal and close this one that relies into details of old implementation

**Comment by dvsrepo** [comment]
Yes, batch prediction should be revisited in a new issue.
