### ISSUE TITLE
Text Transform component

### ISSUE THREAD

**Issue by frascuchon** [recognai/biome-text#112]
Define a common clean pipeline that converts html content into extracted textual data.

**Comment by dcfidalgo** [comment]
After talking to @frascuchon the idea is to create a new "DataCleaner" class (name is still to be decided) that inherits from AllenNLP's `Registrable`.
We can then add custom classes of this DataCleaner in the config file that implement certain cleaning methods that will be applied.

**Comment by dvsrepo** [comment]
Discussed with David to:

1. Take into account the design of other libraries:
   - https://pytorch.org/docs/stable/torchvision/transforms.html
   - https://www.tensorflow.org/tfx/transform/get_started
   - https://dev.fast.ai/text.core#Preprocessing-rules (fastai v2)
  - https://docs.fast.ai/text.transform.html (fastai v1)

2. Allow extensibility by letting developers define their own Transform in their own modules (without using --include-package if possible)
