### ISSUE TITLE
Trainer configurations

### ISSUE THREAD

**Issue by dcfidalgo** [recognai/biome-text#136]
@frascuchon @dvsrepo I propose to expose these two options in the `TrainerConfiguration` class:

```yaml
num_serialized_models_to_keep: 1
should_log_learning_rate: true
```

or maybe hardcode them as defaults, i always include them in my training runs.

**Comment by dvsrepo** [comment]
I agree those are useful, I vote for exposing them and set these values as
default.

Best,

**Comment by frascuchon** [comment]
Hi, another one? Regarding the original train method if found this one that could be a "nice to have"

https://github.com/allenai/allennlp/blob/v0.9.0/allennlp/commands/fine_tune.py#L288

**Comment by frascuchon** [comment]
> Hi, another one? Regarding the original train method if found this one that could be a "nice to have"
> 
> https://github.com/allenai/allennlp/blob/v0.9.0/allennlp/commands/fine_tune.py#L288

I think this should be treated as a separated issue/feature that concerns to fine tuning and gradual unfreeze techniques
