### ISSUE TITLE
notebook usage - stdout in same cell as train command

### ISSUE THREAD

**Issue by dcfidalgo** [recognai/biome-text#137]
When running a training in a cell:
```python
trained_pl = pl.train(..., verbose=True)
```
all subsequent cell outputs go into the cell output of the above command ...
![Screenshot 2020-05-06 at 16 10 59](https://user-images.githubusercontent.com/15979778/81187396-4bfd5400-8fb4-11ea-864c-de3e132a14e2.png)

**Comment by frascuchon** [comment]
I think the reason is the "coolest" way of allennlp logs configuration. Can you reproduce using `verbose=False`

**Comment by dcfidalgo** [comment]
@frascuchon Sorry, just saw your reply now :/ 
Setting verbose to False does not change the behavior
![Screenshot 2020-05-14 at 21 44 57](https://user-images.githubusercontent.com/15979778/81978913-7d1cfa80-962c-11ea-9004-6468d26e8fa9.png)
