### ISSUE TITLE
Review of vocab and extend_vocab related params

### ISSUE THREAD

**Issue by dvsrepo** [recognai/biome-text#139]
I have been testing vocab related params and have a few comments:

## Params

- `vocab_config`: Creating a Pipeline with a vocabulary with `Pipeline.from_config` and `pipeline.from_file` using `VocabularyConfiguration`. Useful for filtering unusual words (min_count) and other things.

- `vocab`: in `pipeline.train` to launch a training experiment with an instantiated pipeline. Useful for reusing an existing vocabulary avoiding its creation during training. From my tests, **this param seems to be ignored**. For example, if I create a pipeline **without** vocab_config, thus I have an empty vocab within the pipeline. Then if I want to pass a pre-generated vocab like this:

```python
# vocab creation with:
...
vocab_config=VocabularyConfiguration(sources=[train, validation], min_count={'words': 10}),
..
pl.save_vocab('vocabulary_min_count_10')

pipe = pl.train(
    output='experiment_pretraining_preproc',
    trainer=TrainerConfiguration(optimizer='adam',num_epochs=5, patience=3),
    training='data/tweets-spanish/train.yml',
    validation='data/tweets-spanish/validation.yml',
    vocab='vocabulary_min_count_10/', 
    extend_vocab=False
)
```
The vocab param will be ignored and my train run will use an empty vocab (only with @unknown and other predefined tokens).

- `extend_vocab`: This param has `default=False` everywhere except in the entry method (`train`). I am not sure if there's a reason to have it as default=True. But **I would vote for having it `False`** in pipeline.train as well. With my tests, this can cause strange behaviours if not taken care, like increasing the sizes of an existing model embeddings and failing only after training during the `pipeline.__class__(
            pretrained_path=os.path.join(config.output, "model.tar.gz"),
            config=pipeline.config,
        )` step.

**Comment by frascuchon** [comment]
Ok, this part is not quite upgrade from old API.

In my point of view, the `VocabConfiguration` brings all needed mechanisms for create/extend the  model vocab. So the related vocab params in training should be dropped out
