### ISSUE TITLE
Remove old docs folder

### ISSUE THREAD

**Issue by dvsrepo** [recognai/biome-text#151]
Can we safely remove the old `docs` folder @dcfidalgo ?

**Comment by dcfidalgo** [comment]
Yes, i will delete it.
@dvsrepo I would also suggest to rename the `documentation` folder to `docs`. Should i do it in the same PR?

**Comment by dvsrepo** [comment]
Yes, we just need to make sure the docs buildings has all references updated to docs instead of documentation

**Comment by dcfidalgo** [comment]
Done in #160. Closing this issue.
