### ISSUE TITLE
Include tokenization results as part of explain result for all models

### ISSUE THREAD

**Issue by frascuchon** [recognai/biome-text#167]

**Comment by dcfidalgo** [comment]
I am not sure if the result of the tokenizer should go hand in hand with the attributions in the explain part of the model.

I could image that especially in the beginning of an experiment, when you try to overfit a small dataset, we are note really interested in the attributions, but we could be interested in the way the tokenizer handles the input. Also, i guess for heavy models the calculation of the attributions could be computing intensive (this also depends on how accurately you want to calculate the attributions.)

**Comment by frascuchon** [comment]
> I am not sure if the result of the tokenizer should go hand in hand with the attributions in the explain part of the model.
> 
> I could image that especially in the beginning of an experiment, when you try to overfit a small dataset, we are note really interested in the attributions, but we could be interested in the way the tokenizer handles the input. Also, i guess for heavy models the calculation of the attributions could be computing intensive (this also depends on how accurately you want to calculate the attributions.)

Issue refers in terrms of prediction explanation. The `explain` should include info about tokenization/featurization (the input to token transformation) and, eventually, the attributions (whatever means that concept for each task).

You can check the related PR
