### ISSUE TITLE
Log INFO:biome.text._model:Serialization directory already exists even with fresh experiments

### ISSUE THREAD

**Issue by dvsrepo** [recognai/biome-text#172]
We need to review this log message:

INFO:biome.text._model:Serialization directory (fine_tuning_boe_avg_0.001) already exists and is not empty.

It is shown every time when running `pipeline.train` even with fresh output directories.

**Comment by frascuchon** [comment]
@dvsrepo Is this issue still in effect?

**Comment by dvsrepo** [comment]
I have checked and dont see this msg anymore
