### ISSUE TITLE
number of `trainable_parameters` not the same

### ISSUE THREAD

**Issue by dcfidalgo** [recognai/biome-text#178]
The number shown in the training log (`verbose=True`) of the number of trainable parameters is slightly different of the number in `Pipeline.trainable_parameters`.

In my example the difference is: 267170 <-> 264226

**Comment by frascuchon** [comment]
The trick here is the train method will extend model vocab, expanding the model backbone embedding sizes, so the resulting number is different to before vocab extension.

**Comment by dcfidalgo** [comment]
ah ok. I just checked and after calling the `train` method (and hence expanding the vocab), the numbers are the same 👍 . Closing this issue.
