### ISSUE TITLE
Tokenized inputs in Explore output to align with new Explore UI

### ISSUE THREAD

**Issue by dvsrepo** [recognai/biome-text#241]
**Is your feature request related to a problem? Please describe.**

Send tokenized inputs to Explore UI (same structure as explain) independently of having the explain=True enable when running pipeline.explore().

The new design of explore should show the same structure with or without attributions.

**Comment by frascuchon** [comment]
@dvsrepo can we close this issue ?  I think is already implemented when `explain=True`
