### ISSUE TITLE
[BUG] Fix js vulnerabilities for ui

### ISSUE THREAD

**Issue by frascuchon** [recognai/biome-text#246]
# Describe the bug
When build ui static files a set of vulnerabilities are reported:

```shell
39 packages are looking for funding
  run `npm fund` for details

found 11 vulnerabilities (8 low, 1 moderate, 2 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
```

## To Reproduce
Just launch ui build:
```shell
make ui
```

## Expected behavior
No vulnerabilities shown

## OS environment
 - OS:  macOS
 - biome.text Version : 1.0.0rc

**Comment by dvsrepo** [comment]
Hi @leiyre have you taken a look at this?
