### ISSUE TITLE
Access spaCy tokenizer within TextCleaningRules

### ISSUE THREAD

**Issue by dvsrepo** [recognai/biome-text#266]
**Is your feature request related to a problem? Please describe.**

Having access to the underlying spaCy tokenizer would enable more powerful text cleaning rules for things like using token attributes like LIKE_EMAIL to replace or emails by a fixed token (e.g., @email).

**Describe the solution you'd like**
When defining text cleaning rules I can use something like `self.tokenizer(text)`

**Comment by frascuchon** [comment]
You could define your own `TextCleaning` implementation:

```python
@TextCleaning.register("spacy")
class DefaultTextCleaning(TextCleaning):
    def __init__(self, lang: str="en"):
      self.nlp = ....# load your spacy model as you want

    def __call__(self, text: str) -> str:
        doc = self.nlp(text)
        .....
```

 and use it in confifuration:
```yaml
tokenizer:
  text_cleaning: 
    type: spacy
    lang: en
....
```

**Comment by dvsrepo** [comment]
OK, we can close this one
