### ISSUE TITLE
Ignore Labels when sorting alphabetically

### ISSUE THREAD

**Issue by dcfidalgo** [recognai/biome-text#273]
**Is your feature request related to a problem? Please describe.**
When starting to explore a data set in the UI, i would like to get a feeling of how the models performs in general. Since the entries are alphabetically sorted including the label, the first entries are all about the same label.  

**Describe the solution you'd like**
Maybe being able to completely randomize the entries, or ignore the label when sorting alphabetically.

@leiyre @dvsrepo @amelie_is_not_on_github?

**Comment by dvsrepo** [comment]
@leiyre could you take a look at this? We should have a default sorting key (ideally no sort at all , otherwise sort by confidence DESCENDING?

**Comment by leiyre** [comment]
@dvsrepo @dcfidalgo The records are initially sorted by default and "default" is a selectable option on dropdown too.

**Comment by dcfidalgo** [comment]
@leiyre Thanks a lot,  works perfectly!
