### ISSUE TITLE
Make links absolute in tutorials

### ISSUE THREAD

**Issue by dcfidalgo** [recognai/biome-text#274]
**Is your feature request related to a problem? Please describe.**
When following a tutorial in Google Colab, the links do not work.

**Describe the solution you'd like**
Make links absolute so that they work in Google Colab

**Comment by dvsrepo** [comment]
can we close this one?

**Comment by dcfidalgo** [comment]
Yes, let's close this one. I think the effort of maintaining absolute links does not justify the additional value of working internal links in Colab ...
