### ISSUE TITLE
Explain loading bars when creating a vocab

### ISSUE THREAD

**Issue by dcfidalgo** [recognai/biome-text#279]
**Is your feature request related to a problem? Please describe.**
When creating a vocab with `Pipeline.create_vocab()` and one has specified a `weights_file` in the word feature pointing to some url, you get three loading bars with no explanation (see screenshot). I think this is confusing for users unfamiliar with AllenNLP.

**Describe the solution you'd like**
Each loading bar should get a small description, something like:
- Creating vocab from data sources
- Downloading pretrained weights file
- Going through pretrained file

**Describe alternatives you've considered**
Maybe use logs comming from AllenNLP?

**Additional context**
![Screenshot from 2020-06-11 19-19-34](https://user-images.githubusercontent.com/15979778/84420733-c146ef00-ac1a-11ea-8c64-b52f91fe4a25.png)

**Comment by dvsrepo** [comment]
@dcfidalgo is this something Ignacio could do? Maybe at the same time we should review other places where progress bars are missing?

**Comment by dcfidalgo** [comment]
This is also related to the new `Dataset` class #398 .

**Comment by dvsrepo** [comment]
Could we close this one?

**Comment by dcfidalgo** [comment]
Since the vocab creation now happens during training the loading bars get explained, since we activate the allennlp logging for the training. -> Closing this one.
