### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by frascuchon** [recognai/biome-text#359]
## Check

* [x] I have tried to find a similar issue and have not found anything which solves my question.

## Description

Does make sense the `segment_sentence` when passing input as a list of strings since text is already splitted?

Refers discussion in this [PR](https://github.com/recognai/biome-text/pull/357)

**Comment by dvsrepo** [comment]
If we are referring to documents with multiple fields (e.g., abstract, content, conclusion) and these fields are part of the input List[str], it could make sense to apply sentence segmentation to each field/block. Having said this, it makes sense logically but we have not encountered a clear use case for this

**Comment by dcfidalgo** [comment]
Also, if we have a 2 level hierarchy, either we have to use a `ListField[ListField[TextField]]` (i think this is not possible) or the forward method takes the fixed values of the first level (abstract, content, conclusion, for example).

**Comment by dcfidalgo** [comment]
Will close this issue, i think for now it does not make sense. When we encounter a use case with a 2 level hierarchy we can come back to this.
