### ISSUE TITLE
[BUG] Community docs are not rendered

### ISSUE THREAD

**Issue by dvsrepo** [recognai/biome-text#369]
# Describe the bug
Community docs in readme.md (https://github.com/recognai/biome-text/tree/master/docs/docs/documentation/community) are not shown in https://www.recogn.ai/biome-text/documentation/. Also there's a broken link at the end of that section: "For development installations, contributing or getting help see the [Community](https://www.recogn.ai/biome-text/community/) section."

## To Reproduce
1. Code snippet or gist.
2. Error message(s) if applicable

## OS environment
- OS: [e.g. Linux / Windows / macOS]
 - biome.text Version [e.g. 1.0.0]

**Comment by dcfidalgo** [comment]
Just saw this issue, i actually just renamed the `readme.md` file to `contributing.md` ... just to let you know @leiyre

**Comment by dcfidalgo** [comment]
Just saw that the renaming seems to fix the issue ... https://www.recogn.ai/biome-text/documentation/community/contributing.html
