### ISSUE TITLE
[BUG] Loading window when applying filters / filters do not work

### ISSUE THREAD

**Issue by dcfidalgo** [recognai/biome-text#383]
# Describe the bug
When applying filters in the UI, there is a loading frame at the top of the entries (see screenshots), and the filters do not seem to work.

## To Reproduce
Run a `Pipeline.explore()` command with `explain=True`, for example in our first tutorial.

## Expected behavior
No loading window at the top

## Screenshots
![Screenshot from 2020-10-02 19-32-48](https://user-images.githubusercontent.com/15979778/94952387-31d58c80-04e6-11eb-948e-37651ae93e12.png)
![Screenshot from 2020-10-02 19-33-02](https://user-images.githubusercontent.com/15979778/94952389-326e2300-04e6-11eb-92b4-dde6bf4fac97.png)

## OS environment
- OS: Linux
 - biome.text Version: master

**Comment by dvsrepo** [comment]
This seems like filter queries are not working, can you check and paste here the network calls to Elasticsearch using the inspect util in your browser?

**Comment by dcfidalgo** [comment]
In the "console" i get a bunch of `TypeError: t.gold is undefined` errors. In the "network" (when i reload with the filters activated) i get a 404 for the last POST call (file: _search).
If you want me to provide more information please let me know!

**Comment by leiyre** [comment]
@frascuchon can you have a look to Elasticsearch call?

**Comment by dcfidalgo** [comment]
I found out that switching from ES 7.9.2 to 7.3.2 solved the issue! Closing.
