### ISSUE TITLE
[BUG] Explore UI seems a bit off in current master

### ISSUE THREAD

**Issue by dcfidalgo** [recognai/biome-text#389]
# Describe the bug
The Confidence histogram is missing in the UI for old indexes (before #382 and #273).
When indexing a new explore (current master) the whole UI seems a bit off (see screenshots).

## To Reproduce
Open some explore with an old and new index.

## Expected behavior
There should be a Confidence histogram

## Screenshots
old index - missing histogram
![Screenshot from 2020-10-07 12-50-36](https://user-images.githubusercontent.com/15979778/95321832-e0d5e780-089b-11eb-9b5d-e38a3d9dea8e.png)

new index - UI off
![Screenshot from 2020-10-07 12-57-09](https://user-images.githubusercontent.com/15979778/95322449-ccdeb580-089c-11eb-96b9-706e5a73d472.png)

## OS environment
- OS: Linux
 - biome.text Version: master

## Additional context
Probably related to the latest changes in #382

**Comment by frascuchon** [comment]
@dcfidalgo Did you test in dev mode ? In that case, did you upgrade the ui components with `make ui` command?

I've launched the UI locally with old explorations and works like a charm

**Comment by dcfidalgo** [comment]
#390 fixes the issue with the new explorations
