### ISSUE TITLE
ImportError: cannot import name 'Dataset' from 'biome.text'

### ISSUE THREAD

**Issue by TitusHora** [recognai/biome-text#446]
# Describe the bug
I am trying to do the "Training a short text classifier of German business names" tutorial and I get the following error:
ImportError: cannot import name 'Dataset' from 'biome.text'
## To Reproduce
1. from biome.text import Dataset
2.ImportError: cannot import name 'Dataset' from 'biome.text' (/home/titus/anaconda3/envs/biome/lib/python3.7/site-packages/biome/text/__init__.py)

## Expected behavior
import Dataset
## OS environment
- OS: Ubuntu 20.04
![import Dataset error](https://user-images.githubusercontent.com/19308140/99354935-ab171c00-28a7-11eb-8c4e-0695f408862f.png)

 - biome.text Version [e.g. 1.0.0]

**Comment by dvsrepo** [comment]
Hi,

`Dataset` has been recently introduced and not available for previous
releases (like 1.0).

Could you try to pip install from master? You could run the first cell in
the tutorial and restart the kernel if you are using jupyter. Please tell
us if you can solve it like that or we can give you more details.

**Comment by TitusHora** [comment]
Hi,
Thank you for responding.
Yes, please give me more details about what to do.
I'm not sure what '...pip install from master' means.

New to this.

Much appreciated, thank you!

**Comment by dcfidalgo** [comment]
Hi,
Thanks for reporting! 

To install from master you just need to type:
```terminal
pip install -U git+https://github.com/recognai/biome-text.git
```
in your terminal after activating you conda environment.

We will surely make a release soon, so installing from master should not be necessary in the near future. Sorry for the inconvenience!

**Comment by TitusHora** [comment]
Thank you, no worries!
Much appreciated!
