### ISSUE TITLE
[Tutorials] Add tip about readingTune analysis from experiment dir

### ISSUE THREAD

**Issue by dvsrepo** [recognai/biome-text#521]
I have to look up this every time and it's somehow not very accessible in tune docs:

```python
from ray.tune.analysis.experiment_analysis import Analysis
results = Analysis(experiment_dir='base_hpo/Baseline profner classifier', 
                   default_metric='validation_accuracy',
                   default_mode='max'
)
```
It's often the case that you have this long running HPO process and you want to revisit and analyse the results at a later stage,  the `analysis = tune.run()..` it's the ideal case for very quick HPO processes, but I guess reading from dir is much more frequent. This is a tune thing but I think it adds value to the tutorials where we have HPO stuff.

**Comment by dcfidalgo** [comment]
I wasn't even aware of this possibility ... :) i added it to the hpo tutorial in #522 ! Thanks for mentioning it!
