### ISSUE TITLE
[BUG] WandB FileNotFoundError

### ISSUE THREAD

**Issue by ignacioct** [recognai/biome-text#538]
# Describe the bug
When training and logging into wandb, we are obtaining a FileNotFoundError, as wandb cannot find a directory.

## To Reproduce
Training (or making HPO in my case) and logging data into wandb in Google Colab. Maybe this only happens with HPOs? I don't think so, as this come from biome.

`Traceback (most recent call last):
(pid=1051)   File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_init.py", line 745, in init
(pid=1051)     run = wi.init()
(pid=1051)   File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_init.py", line 541, in init
(pid=1051)     run._on_start()
(pid=1051)   File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_run.py", line 1544, in _on_start
(pid=1051)     self._console_start()
(pid=1051)   File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_run.py", line 1517, in _console_start
(pid=1051)     self._output_writer = WriteSerializingFile(open(output_log_path, "wb"))
(pid=1051) FileNotFoundError: [Errno 2] No such file or directory: '.wandb/.wandb/run-20210327_201513-1ptl8exi/files/output.log'
(pid=1051) 
(pid=1051) Problem at: /usr/local/lib/python3.7/dist-packages/biome/text/loggers.py 254 init_train
wandb:                                                                                
(pid=1051) wandb: ERROR Abnormal program exit`

## OS environment
- Google Collab
 - biome.text latest commit

**Comment by ignacioct** [comment]
As long as I understand, this bug is not happening anymore with the new trainer, right @dcfidalgo ?

**Comment by dcfidalgo** [comment]
Old trainer was removed, closing this.
