### ISSUE TITLE
[BUG] trainer.fit() does not create a directory if path is specified

### ISSUE THREAD

**Issue by ignacioct** [recognai/biome-text#580]
# Describe the bug/thing
Not sure if it's a bug. If you make trainer.fit(), it will automatically create a default output directory. If a directory is specified, and it does exist, there no problem either. However, specifying a directory that doesn't exist does not create the directory (which is kind of what intuition says, right?). Not sure if its intentional or not, we can discuss it and correct it as a bug if it is not intentional @dcfidalgo @dvsrepo.

## To Reproduce
`trainer.fit("output/some_non_existing_directory")`

## Expected behavior
Intuition says to me that 'some_non_existing_directory' should be created if it does not exists

## OS environment
- OS: macOS
 - biome.text Version 3.2.1

**Comment by dcfidalgo** [comment]
Definitely a bug! Thanks for reporting! It did not create non existing parent dirs, fixed it in #581.
